/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.lang.instrument.Instrumentation;

import java.util.concurrent.CountDownLatch;

public class Agent {
	public static CountDownLatch countDownLatch = new CountDownLatch(1);

	static {
		System.out.println("agent static: "+countDownLatch.getCount());
	}

	public static void premain(String args, Instrumentation instrumentation) {
		System.out.println("agent enter: "+countDownLatch.getCount());
		countDownLatch.countDown();
		System.out.println("agent exit: "+countDownLatch.getCount());
    }
}
